/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.pgcc.eseco.domain.dao.core;

import br.ufjf.pgcc.eseco.common.dao.CommonDAO;
import br.ufjf.pgcc.eseco.domain.model.core.Country;
import org.springframework.stereotype.Repository;

/**
 *
 * @author Lenita
 */
@Repository
public class CountryDAO extends CommonDAO<Country, Integer> {

    public CountryDAO() {
        super(Country.class);
    }
    
    

    public void populateCountries() throws Exception {
        add(new Country("Afghanistan", "AF"));
        add(new Country("AlandIslands", "AX"));
        add(new Country("Albania", "AL"));
        add(new Country("Algeria", "DZ"));
        add(new Country("AmericanSamoa", "AS"));
        add(new Country("Andorra", "AD"));
        add(new Country("Angola", "AO"));
        add(new Country("Anguilla", "AI"));
        add(new Country("Antarctica", "AQ"));
        add(new Country("AntiguaandBarbuda", "AG"));
        add(new Country("Argentina", "AR"));
        add(new Country("Armenia", "AM"));
        add(new Country("Aruba", "AW"));
        add(new Country("Australia", "AU"));
        add(new Country("Austria", "AT"));
        add(new Country("Azerbaijan", "AZ"));
        add(new Country("Bahamas", "BS"));
        add(new Country("Bahrain", "BH"));
        add(new Country("Bangladesh", "BD"));
        add(new Country("Barbados", "BB"));
        add(new Country("Belarus", "BY"));
        add(new Country("Belgium", "BE"));
        add(new Country("Belize", "BZ"));
        add(new Country("Benin", "BJ"));
        add(new Country("Bermuda", "BM"));
        add(new Country("Bhutan", "BT"));
        add(new Country("Bolivia", "BO"));
        add(new Country("BosniaandHerzegovina", "BA"));
        add(new Country("Botswana", "BW"));
        add(new Country("BouvetIsland", "BV"));
        add(new Country("Brazil", "BR"));
        add(new Country("BritishVirginIslands", "VG"));
        add(new Country("BritishIndianOceanTerritory", "IO"));
        add(new Country("BruneiDarussalam", "BN"));
        add(new Country("Bulgaria", "BG"));
        add(new Country("BurkinaFaso", "BF"));
        add(new Country("Burundi", "BI"));
        add(new Country("Cambodia", "KH"));
        add(new Country("Cameroon", "CM"));
        add(new Country("Canada", "CA"));
        add(new Country("CapeVerde", "CV"));
        add(new Country("CaymanIslands", "KY"));
        add(new Country("CentralAfricanRepublic", "CF"));
        add(new Country("Chad", "TD"));
        add(new Country("Chile", "CL"));
        add(new Country("China", "CN"));
        add(new Country("HongKong,SARChina", "HK"));
        add(new Country("Macao,SARChina", "MO"));
        add(new Country("ChristmasIsland", "CX"));
        add(new Country("Cocos(Keeling)Islands", "CC"));
        add(new Country("Colombia", "CO"));
        add(new Country("Comoros", "KM"));
        add(new Country("Congo (Brazzaville)", "CG"));
        add(new Country("Congo,(Kinshasa)", "CD"));
        add(new Country("CookIslands", "CK"));
        add(new Country("CostaRica", "CR"));
        add(new Country("Côted'Ivoire", "CI"));
        add(new Country("Croatia", "HR"));
        add(new Country("Cuba", "CU"));
        add(new Country("Cyprus", "CY"));
        add(new Country("CzechRepublic", "CZ"));
        add(new Country("Denmark", "DK"));
        add(new Country("Djibouti", "DJ"));
        add(new Country("Dominica", "DM"));
        add(new Country("DominicanRepublic", "DO"));
        add(new Country("Ecuador", "EC"));
        add(new Country("Egypt", "EG"));
        add(new Country("ElSalvador", "SV"));
        add(new Country("EquatorialGuinea", "GQ"));
        add(new Country("Eritrea", "ER"));
        add(new Country("Estonia", "EE"));
        add(new Country("Ethiopia", "ET"));
        add(new Country("FalklandIslands(Malvinas)", "FK"));
        add(new Country("FaroeIslands", "FO"));
        add(new Country("Fiji", "FJ"));
        add(new Country("Finland", "FI"));
        add(new Country("France", "FR"));
        add(new Country("FrenchGuiana", "GF"));
        add(new Country("FrenchPolynesia", "PF"));
        add(new Country("FrenchSouthernTerritories", "TF"));
        add(new Country("Gabon", "GA"));
        add(new Country("Gambia", "GM"));
        add(new Country("Georgia", "GE"));
        add(new Country("Germany", "DE"));
        add(new Country("Ghana", "GH"));
        add(new Country("Gibraltar", "GI"));
        add(new Country("Greece", "GR"));
        add(new Country("Greenland", "GL"));
        add(new Country("Grenada", "GD"));
        add(new Country("Guadeloupe", "GP"));
        add(new Country("Guam", "GU"));
        add(new Country("Guatemala", "GT"));
        add(new Country("Guernsey", "GG"));
        add(new Country("Guinea", "GN"));
        add(new Country("Guinea-Bissau", "GW"));
        add(new Country("Guyana", "GY"));
        add(new Country("Haiti", "HT"));
        add(new Country("HeardandMcdonaldIslands", "HM"));
        add(new Country("HolySee (VaticanCityState)", "VA"));
        add(new Country("Honduras", "HN"));
        add(new Country("Hungary", "HU"));
        add(new Country("Iceland", "IS"));
        add(new Country("India", "IN"));
        add(new Country("Indonesia", "ID"));
        add(new Country("Iran,IslamicRepublicof", "IR"));
        add(new Country("Iraq", "IQ"));
        add(new Country("Ireland", "IE"));
        add(new Country("IsleofMan", "IM"));
        add(new Country("Israel", "IL"));
        add(new Country("Italy", "IT"));
        add(new Country("Jamaica", "JM"));
        add(new Country("Japan", "JP"));
        add(new Country("Jersey", "JE"));
        add(new Country("Jordan", "JO"));
        add(new Country("Kazakhstan", "KZ"));
        add(new Country("Kenya", "KE"));
        add(new Country("Kiribati", "KI"));
        add(new Country("Korea (North)", "KP"));
        add(new Country("Korea (South)", "KR"));
        add(new Country("Kuwait", "KW"));
        add(new Country("Kyrgyzstan", "KG"));
        add(new Country("LaoPDR", "LA"));
        add(new Country("Latvia", "LV"));
        add(new Country("Lebanon", "LB"));
        add(new Country("Lesotho", "LS"));
        add(new Country("Liberia", "LR"));
        add(new Country("Libya", "LY"));
        add(new Country("Liechtenstein", "LI"));
        add(new Country("Lithuania", "LT"));
        add(new Country("Luxembourg", "LU"));
        add(new Country("Macedonia,Republicof", "MK"));
        add(new Country("Madagascar", "MG"));
        add(new Country("Malawi", "MW"));
        add(new Country("Malaysia", "MY"));
        add(new Country("Maldives", "MV"));
        add(new Country("Mali", "ML"));
        add(new Country("Malta", "MT"));
        add(new Country("MarshallIslands", "MH"));
        add(new Country("Martinique", "MQ"));
        add(new Country("Mauritania", "MR"));
        add(new Country("Mauritius", "MU"));
        add(new Country("Mayotte", "YT"));
        add(new Country("Mexico", "MX"));
        add(new Country("Micronesia,FederatedStatesof", "FM"));
        add(new Country("Moldova", "MD"));
        add(new Country("Monaco", "MC"));
        add(new Country("Mongolia", "MN"));
        add(new Country("Montenegro", "ME"));
        add(new Country("Montserrat", "MS"));
        add(new Country("Morocco", "MA"));
        add(new Country("Mozambique", "MZ"));
        add(new Country("Myanmar", "MM"));
        add(new Country("Namibia", "NA"));
        add(new Country("Nauru", "NR"));
        add(new Country("Nepal", "NP"));
        add(new Country("Netherlands", "NL"));
        add(new Country("NetherlandsAntilles", "AN"));
        add(new Country("NewCaledonia", "NC"));
        add(new Country("NewZealand", "NZ"));
        add(new Country("Nicaragua", "NI"));
        add(new Country("Niger", "NE"));
        add(new Country("Nigeria", "NG"));
        add(new Country("Niue", "NU"));
        add(new Country("NorfolkIsland", "NF"));
        add(new Country("NorthernMarianaIslands", "MP"));
        add(new Country("Norway", "NO"));
        add(new Country("Oman", "OM"));
        add(new Country("Pakistan", "PK"));
        add(new Country("Palau", "PW"));
        add(new Country("PalestinianTerritory", "PS"));
        add(new Country("Panama", "PA"));
        add(new Country("PapuaNewGuinea", "PG"));
        add(new Country("Paraguay", "PY"));
        add(new Country("Peru", "PE"));
        add(new Country("Philippines", "PH"));
        add(new Country("Pitcairn", "PN"));
        add(new Country("Poland", "PL"));
        add(new Country("Portugal", "PT"));
        add(new Country("PuertoRico", "PR"));
        add(new Country("Qatar", "QA"));
        add(new Country("Réunion", "RE"));
        add(new Country("Romania", "RO"));
        add(new Country("RussianFederation", "RU"));
        add(new Country("Rwanda", "RW"));
        add(new Country("Saint-Barthélemy", "BL"));
        add(new Country("SaintHelena", "SH"));
        add(new Country("SaintKittsandNevis", "KN"));
        add(new Country("SaintLucia", "LC"));
        add(new Country("Saint-Martin(Frenchpart)", "MF"));
        add(new Country("SaintPierreandMiquelon", "PM"));
        add(new Country("SaintVincentandGrenadines", "VC"));
        add(new Country("Samoa", "WS"));
        add(new Country("SanMarino", "SM"));
        add(new Country("SaoTomeandPrincipe", "ST"));
        add(new Country("SaudiArabia", "SA"));
        add(new Country("Senegal", "SN"));
        add(new Country("Serbia", "RS"));
        add(new Country("Seychelles", "SC"));
        add(new Country("SierraLeone", "SL"));
        add(new Country("Singapore", "SG"));
        add(new Country("Slovakia", "SK"));
        add(new Country("Slovenia", "SI"));
        add(new Country("SolomonIslands", "SB"));
        add(new Country("Somalia", "SO"));
        add(new Country("SouthAfrica", "ZA"));
        add(new Country("SouthGeorgiaandtheSouthSandwichIslands", "GS"));
        add(new Country("SouthSudan", "SS"));
        add(new Country("Spain", "ES"));
        add(new Country("SriLanka", "LK"));
        add(new Country("Sudan", "SD"));
        add(new Country("Suriname", "SR"));
        add(new Country("SvalbardandJanMayenIslands", "SJ"));
        add(new Country("Swaziland", "SZ"));
        add(new Country("Sweden", "SE"));
        add(new Country("Switzerland", "CH"));
        add(new Country("SyrianArabRepublic (Syria)", "SY"));
        add(new Country("Taiwan,RepublicofChina", "TW"));
        add(new Country("Tajikistan", "TJ"));
        add(new Country("Tanzania,UnitedRepublicof", "TZ"));
        add(new Country("Thailand", "TH"));
        add(new Country("Timor-Leste", "TL"));
        add(new Country("Togo", "TG"));
        add(new Country("Tokelau", "TK"));
        add(new Country("Tonga", "TO"));
        add(new Country("TrinidadandTobago", "TT"));
        add(new Country("Tunisia", "TN"));
        add(new Country("Turkey", "TR"));
        add(new Country("Turkmenistan", "TM"));
        add(new Country("TurksandCaicosIslands", "TC"));
        add(new Country("Tuvalu", "TV"));
        add(new Country("Uganda", "UG"));
        add(new Country("Ukraine", "UA"));
        add(new Country("UnitedArabEmirates", "AE"));
        add(new Country("UnitedKingdom", "GB"));
        add(new Country("UnitedStatesofAmerica", "US"));
        add(new Country("USMinorOutlyingIslands", "UM"));
        add(new Country("Uruguay", "UY"));
        add(new Country("Uzbekistan", "UZ"));
        add(new Country("Vanuatu", "VU"));
        add(new Country("Venezuela (BolivarianRepublic)", "VE"));
        add(new Country("VietNam", "VN"));
        add(new Country("VirginIslands,US", "VI"));
        add(new Country("WallisandFutunaIslands", "WF"));
        add(new Country("WesternSahara", "EH"));
        add(new Country("Yemen", "YE"));
        add(new Country("Zambia", "ZM"));
        add(new Country("Zimbabwe", "ZW"));
    }
}
